vlabs_cms_admin_category:
    resource: "@VlabsCmsBundle/Resources/config/routing/admin/category.yml"
    prefix: /

vlabs_cms_admin_post:
    resource: "@VlabsCmsBundle/Resources/config/routing/admin/post.yml"
    prefix: /post

vlabs_cms_admin_summernote:
    resource: "@VlabsCmsBundle/Resources/config/routing/admin/summernote.yml"
    prefix: /summernote
